services:

  frontend:

    build:
      context: ./frontend

    container_name: frontend_react

    working_dir: /app

    user: node

    volumes:
      - ./frontend:/app
      # - frontend_node_modules:/app/node_modules

    ports:
      - "5173:5173"

    tty: true

    stdin_open: true

    networks:
      - localnet

    # command: tail -f /dev/null
    command: npm run dev -- --host 0.0.0.0 --port 5173

  mysql:
    image: mariadb:latest

    container_name: mysql-container-sekripsi

    ports:
      - "3306:3306"

    environment:
      MARIADB_ROOT_PASSWORD: susah_diingat
      TZ: Asia/Makassar

    volumes:
      - ./mysql/data:/var/lib/mysql

    restart: unless-stopped

    networks:
      - localnet


  fastapi:
    build:
      args:
        user: putu
        uid: 1000
      context: ./backend
    image: my-fastapi-sekripsi
    container_name: fastapi_app_sekripsi
    restart: unless-stopped
    working_dir: /app
    environment:
      TZ: Asia/Makassar
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    networks:
      - localnet
    command: bash -c "bash -u /app/scripts/startup.sh"

  streamlit:
    build:
      context: ./streamlit
      args:
        user: appuser
        uid: 1000

    container_name: streamlit-container

    ports:
      - "8501:8501"

    volumes:
      - ./streamlit:/app

    working_dir: /app

    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      
    depends_on:
      - fastapi
    networks:
      - localnet

  nginx:
    image: nginx:stable-alpine

    container_name: nginx-proxy

    restart: always

    ports:
      - "80:80"

    depends_on:
      - fastapi

    volumes:

      # nginx config
      - ./nginx/conf.d:/etc/nginx/conf.d

      # react build dist
      - ./frontend/dist:/usr/share/nginx/html

      # optional logs
      - ./nginx/logs:/var/log/nginx
    networks:
      - localnet

  phpmyadmin:
    image: phpmyadmin
    container_name: my-phpmyadmin-container
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - TZ=Asia/Makassar
    networks:
      - localnet

networks:
  localnet:
    driver: bridge