"""add email token and expired token for verify email

Revision ID: e40299b486f6
Revises: 0ebb3143f637
Create Date: 2026-06-10 15:29:54.985354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40299b486f6'
down_revision: Union[str, Sequence[str], None] = '0ebb3143f637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_email_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verify_email_expired_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_email_expired_at')
    op.drop_column('users', 'verify_email_token')
    # ### end Alembic commands ###
